-- TripSplit schema compatibility notice
--
-- The database is now defined by the ordered files in `supabase/migrations/`, beginning
-- with `20260701000000_baseline.sql`. This former desired-state script intentionally no
-- longer contains executable DDL: re-running a stale monolithic schema after the release
-- hardening migrations could recreate permissive policies or overwrite secured RPCs.
--
-- Fresh/local database:
--   supabase db reset
--
-- Existing linked database that was originally created from this file:
--   1. Back up and compare the live schema to the baseline.
--   2. Mark 20260701000000 as applied in migration history; do not execute it again.
--   3. Apply the later migrations in order and run the authorization test matrix in
--      SECURITY_APP_STORE_READINESS.md against staging before production.
